### ISSUE TITLE
Best practice to maintain canonical stores?

### ISSUE THREAD

**Issue by marbemac** [Yomguithereal/baobab#128]
I'm running into issues when I start to throw more advanced scenarios at Baobab. I'm hoping somebody has ideas on how to handle these scenarios. An example - let's say I have a tree like this:

```js
var state = new Baobab({
  projects: {
    error: null,
    loading: false,
    data: {}    
  },

  currentProject: {
    error: null,
    loading: false,
    data: null    
  },

  filteredProjects: ???
});
```

Ideally:
projects.data holds all the projects that have been fetched in the life of the application. This is the canonical store for projects. If I change projects.data.123's name, this change should be reflected everywhere in the application.

currentProject.data should point to or hold the data for the currently selected project. filteredProjects should point to or hold a subset of projects.data, depending on the filters the user has chosen.

React view A has a cursor for currentProject. React view B has a cursor for filteredProjects. The problem here is that when a user updates the name of the current project, the app needs to manually update the project name in all three locations (projects.data, currentProject.data, filteredProjects.data). This manual updating can quickly grow out of control. 

I tried setting currentProject.data to a cursor that points to the project in projects.data (basically trying to treat it like a pointer), but the currentProject update event was not fired when the corresponding project in projects.data was updated.

So my questions are:
1) Is there a way to have a cursor point to another cursor, so that data does not need to be duplicated/denormalized (which introduces all sorts of update complexity).
2) Is there a best practice around creating a cursor that includes a subset of the tree data? In the example above, I need a cursor that includes only some of the projects.

Looking forward to hearing your thoughts, and please let me know if the above is confusing or needs more explanation.

**Comment by marbemac** [comment]
@christianalfoni I really enjoyed your blog posts on Baobab. I was wondering if you had any ideas regarding this, or have run into similar issues?

**Comment by christianalfoni** [comment]
Hi @marbemac ,

This is a very good question indeed. It is a problem you meet handling state in any kind of architecture really. Should you allow duplicates and make your setters more complex, or should you use references and make your getters more complex. No right answer, it depends I think, like so many things. But you have made an example with complex setters, so let me give an example with complex getters :-)

```javascript
var tree = new Baobab({
  projects: [{id: 0}, {id: 1}],
  currentProject: 1
});
var MyProjectComponent = React.createClass({
  mixins: [tree.mixin],
  cursors: {
    projects: ['projects'],
    currentProject: ['currentProject']
  },
  render: function () {
    // Using underscore
    var project = _.findWhere(this.state.cursors.projects, {id: this.state.cursors.currentProject});
  }
});
```
It is an interesting idea you have, allowing cursors inside the tree. You could do something like:

var tree = new Baobab({
  projects: [{id: 123}],
  currentProject: null
});

tree.set('currentProject', Baobab.Cursor('projects', {id: 123}));

I am not sure about the consequences etc., maybe @Yomguithereal would like to comment on this?

**Comment by marbemac** [comment]
Thanks for the response! Yeah I tried setting a cursor in the tree. The main issue is that an update to the thing the cursor points at did not trigger an update on the cursor. So if:

```js
tree.set('currentProject', Baobab.Cursor('projects', {id: 123}));
var index = _.findIndex(tree.get('projects'), function(p) { return p.id === 123; });
tree.set(['projects', index, 'name'], 'new name'); 
// currentProject update event not fired.      
```

When the project with id 123 is updated, the update event did not fire on currentProject.

Regarding complex getters, I suppose with the filteredProjects subset question you would do something like this? Basically maintain a separate cursor of filtered ids, and populate from the canonical projects store.

```js
var tree = new Baobab({
  projects: [{id: 0}, {id: 1}, {id: 2}],
  filteredProjects: [0, 2]
});
var MyProjectComponent = React.createClass({
  mixins: [tree.mixin],
  cursors: {
    filteredProjects: ['filteredProjects']
  },
  render: function () {
    // Using underscore
    var projectIds = this.state.cursors.filteredProjects;
    var projects = _.filter(tree.get('projects'), function(p){ return _.contains(projectIds, p.id); });
  }
});
```

**Comment by Yomguithereal** [comment]
Hello @marbemac and @christianalfoni,

In my humble opinion, stocking cursors within the tree seems like a bad idea. The tree, ideally, should only store data (by this I mean serializable data).

Concerning the example presented here, I think that the best way would be to store the projects' data as you currently do and the currentProject as just an id. I don't know the scale of your application but the only case where I imagine it would be relevant to store a filtered fraction of your projects is if you'd have to cache heavy computations or if a component strictly relies on the update on this fraction (which seems to be your case).

So here, we are in fact dealing with a kind of constraints. By this I mean that when the tree is updated, you need to update other parts of it to stay in sync. There are two ways to perform this and I think the second solution is best:

1. listen to project's data change through a cursor and update the filtered list if needed (but this will occur within two renders, which is not ideal).
2. Don't let components update the tree themselves but make them refer to a "central authority" through events or something similar and let this "authority" perform model updates (looks a lot like Flux, in fact). The "authority" will then be able to update the tree in only one stack by filtering the projects if needed.

But finally, concerning the fact that you would like to have a cursor with "dynamic" path (for your currentProject) and because duplicating data seems like a bad idea (would work however, I assume that you want a cursor aiming at firing when the current project's data is updated not just when the current project changes altogether), I am considering the idea of `facets` (thanks @jacomyal) which would work like views of your tree's state and would perfectly accomodate your filteredProjects and currentProjects problems.

Let me think about it a little bit more and fiddle something I can propose to you both so we can discuss it.

**Comment by christianalfoni** [comment]
@marbemac Yup, that was my thought

@Yomguithereal Yeah, this makes sense. Facets seems like an interesting concept!

**Comment by Yomguithereal** [comment]
Ok, what I imagine is the following:

Facets would work exactly like React components but would not render visuals but rather return data. They would therefore consist in functions bound to cursors. Whenever the cursors would fire an update, the data computed by the associated function would consequently update. You would therefore be able to listen to your facet's updates the same way you could do it with cursors.

*Experiment*

```js
var tree = new Baobab(
  
  // State
  {
    projects: [
      {
        id: 1,
        name: 'Tezcatlipoca',
        user: 'John'
      },
      {
        id: 2,
        name: 'Huitzilopochtli',
        user: 'John'
      },
      {
        id: 3,
        name: 'Tlaloc',
        user: 'Jack'
      }
    ],
    currentProjectId: 1
  },

  // Options
  { 

    // Facets
    facets: {

      // Retrieve the current project's data
      currentProject: {
        cursors: {
          projects: ['projects']
        },
        get: function(data) {
          var currentId = this.get('currentProjectId');
          return _.first(data.projects, {id: currentId});
        }
      },

      // Retrieve filtered projects
      filteredProjects: {
        cursors: {
          projects: ['projects']
        },
        get: function(data) {
          return data.projects.filter(function(project) {
            return project.user === 'John';
          });
        }
      }
    }
  }
);
```

This way, your tree only holds actual data without duplication and constraint values and views on the state are expressed clearly. At each tree update, data stored by facets will be updated only if needed according to cursors and the facets will fire an update only if data has changed.

**Comment by RJ** [comment]
I encountered a situation while trying baobab that led me to wanting cursor-pointers too. I have an arbitrary list of channels, identified by an integer key (coming from a serverside database).

    var tree = new Baobab({
      channels: {
        1: {id:1, name: "info1"},
        9: {id:9, name: "info2"},
        42: {id:42, name: "info3"}
      }
      currentChannel: 1
    });

Now say i'm rendering just the current channel, i would like to write something like:

    var CurrentChannel = React.createClass({
      mixins: [tree.mixin],
      cursors: {
        channel: ['channels', {pointer: ['currentChannel']}]
      },
      render: function () {
        ... {this.state.cursors.channel}
      }
    });

I don't want to store pointers in the tree per-se, but use paths within the path. This approach seems like a lot less code for me to write than defining a facet, and I really want the mixin to still be able to deal with subscribing to the cursor etc.

**Comment by christianalfoni** [comment]
Just putting in my two cents!

This looks interesting indeed, though it does add a bit of complexity I think. I say this for three reasons:

1. You have to look at both the tree and the facet to "compose" the dependencies. You would probably put facets in its own file making that "composing" a quite complex operation for your head

2. You have two values for one thing. You just want "currentProject" really, not "currentProjectId"

3. When listening to the Facet you have to listen to all its dependencies. Not only when "projects" change, but also when the "currentProjectId" changes. As I would imagine the use of it would be:

```js
var Comp = React.createClass({
  mixins: [tree.mixin],
  cursors: {
    currentProject: ['currentProject']
  },
  render: function () { ... }
});
```

As I understand it, in this scenario the component would not update when the "currentProjectId" cursor updates, because neither the component or the facet is listening to that.

So thinking about this I have a couple of suggestions. I think it might be an idea to flip this completely around. Instead of a **get** you have a **set**:

```js
var tree = new Baobab({
  projects: []
}, {
  facets: {
    currentProject: {
      cursors: {
        projects: ['projects']
      },
      set: function (id) {
        return _.first(cursors.projects, {id: id});;
      }
    }
  }
});
```
So now you set the value of "currentProject" when changing the "currentProject" cursor. This means that the current getter works just like before. It also makes it easier to control dependencies because now if the "projects" cursor updates you just have to run the setter again, which would trigger the cursor update on "currentProject". A last good thing about this is that you only run the setter once, compared to a getter that might be run several times. Does that make sense?

Finally it is the problem of nesting. You would want to put a facet deeper into the tree, and this does not look very good:

```js
var facets = {
    admin: {
      currentProject: {
        cursors: {
          projects: ['projects']
        },
        set: function (id) {
          return _.first(cursors.projects, {id: id});;
        }
      }
    }
  }
}
```

So I am thinking of two things. Use a function or an "object signature". By "object signature" I mean what Promises do. They just check if the object has a "then" method... then its a promise. You could to the same here, check for cursors object and a set method.

With a function:
```js
var tree = new Baobab({
  projects: [],
  currentProject: function () {
    return {
      cursors: {
        projects: ['projects']
      },
      set: function (id) {
        return _.first(cursors.projects, {id: id});;
      }
    }
  }
});
```

With object signature:
With a function:
```js
var tree = new Baobab({
  projects: [],
  currentProject: {
    cursors: {
      projects: ['projects']
    },
    set: function (id) {
      return _.first(cursors.projects, {id: id});;
    }
  }
});
```

Okay, hopefully all this made sense :-)

**Comment by Yomguithereal** [comment]
Nice idea @RJ, I would probably write it likewise for more clarity however:

```js
var CurrentChannel = React.createClass({
      mixins: [tree.mixin],
      cursors: {
        channel: ['channels', {$cursor: ['currentChannel']}]
      },
      render: function () {
        ... {this.state.cursors.channel}
      }
    });
```

@christianalfoni, let me rewrite my example correctly (I used `this` and realize now should really not):

```js
var tree = new Baobab(

  // State
  {
    projects: [
      {
        id: 1,
        name: 'Tezcatlipoca',
        user: 'John'
      },
      {
        id: 2,
        name: 'Huitzilopochtli',
        user: 'John'
      },
      {
        id: 3,
        name: 'Tlaloc',
        user: 'Jack'
      }
    ],
    currentProjectId: 1
  },

  // Options
  { 

    // Facets
    facets: {

      // Retrieve the current project's data
      currentProject: {
        cursors: {
          projects: ['projects'],
          id: ['currentId']
        },
        get: function(data) {
          return _.first(data.projects, {id: data.id});
        }
      },

      // Retrieve filtered projects
      filteredProjects: {
        cursors: {
          projects: ['projects']
        },
        get: function(data) {
          return data.projects.filter(function(project) {
            return project.user === 'John';
          });
        }
      }
    }
  }
);
```

What I do not like with the **set** approach is that
that it will duplicate data in the tree. What you need in the end is just a list of projects and to know which is the current one, by storing an id, an index or by setting a flag. Everything else is just a way of looking at the data.

I agree that this mean you'll have to look at two separate sources but I was accustomed to fear when some constraints can write the tree besides the external methods explicitly modifying data.

@marbemac, in your case, maybe a flag approach would be better for the time being and before anything is made about this.

```js
var tree = new Baobab({
  projects: [
    {id: 1, name: 'one', current: false},
    {id: 2, name: 'two', current: true},
  ]
});

var cursor = tree.select('projects', {current: true});
```

**Comment by christianalfoni** [comment]
@Yomguithereal Yeah, good point!

:+1:  for

```js
var CurrentChannel = React.createClass({
      mixins: [tree.mixin],
      cursors: {
        channel: ['channels', {$cursor: ['currentChannel']}]
      },
      render: function () {
        ... {this.state.cursors.channel}
      }
    });
```
Very explicit and simple to use :-)

**Comment by marbemac** [comment]
I ended up building a mixin that adds a queries signature to components. It's quite similar to the facets idea you present above. However, I find that defining the data a component is looking for, on the component itself, makes for more understandable code (rather than having these definitions in a facets object in the tree definition). 

For each defined query on the component, the query mixin first tries to call query.local (passing in the defined cursors). If no result from query.local, try query.remote. Query.remote should call an action that triggers an update on one of the cursors the query is listening to. In my case it fires off an API request to fetch the channel data, then adds the channel to the tree.channels object (which causes an update on the cursor the query is listening to). When that update is triggered, the query will again call query.local, which should now return the channel.

The signature looks like this:

```js
var CurrentChannel = React.createClass({
  mixins: [ StateQuery.mixin ],
  queries: {
    currentChannel: {
      cursors: {
        channels: ['channels'],
        channelId: ['currentChannelId']
      },
      local: function(data) {
        // Some function that looks through tree.channels and returns the channel if found.
        // Use lodash or something.
        return StateQuery.findOne(data.channels.get(), {id: data.channelId.get()});
      },
      remote: function(data) {
        // Some action that fetches (most likely via an api) the currentChannel, and 
        // then adds it to the tree.channels object
        return StateActions.findOne(StateActions.models.CHANNEL, data.channelId.get());
      }
    }
  },
  render: function() {
    if (this.state.currentChannel.loading) {
      return <div>Loading...</div>;
    }

    // handle errors somehow? this.state.currentChannel.error?
    
    return <div>My channel is {this.state.currentChannel.result.name}</div>;
  }
});
```

I can put the full implementation in a gist if anybody is interested.

**Comment by JohnPostlethwait** [comment]
@marbemac I'd love to see the Gist!

**Comment by marbemac** [comment]
@JohnPostlethwait sure thing, see: 
https://gist.github.com/marbemac/a18582da8d2912285950.

The important file is mixins.js:
https://gist.github.com/marbemac/a18582da8d2912285950#file-mixins-js

The rest of the files there demonstrate my specific implementation. The main thing to be aware of is the query.local function should return data immediately (looking it up however you want, with lodash, etc). The query.remote function should return a promise that resolves on fetch success and rejects (with error) on error. If query.remote rejects, then query.{queryKey}.error will be set to the rejected error.

Let me know if you have any questions!

**Comment by JohnPostlethwait** [comment]
That's fantastic, thanks a lot @marbemac! We are researching using Baobab for a very similar use-case, this helps a lot!

**Comment by marbemac** [comment]
@JohnPostlethwait I was running into conflict issues with the regular Baobab stateTree.mixin, so I namespaced all of the query specific variables. I also exposed query.cursors. You can see all the updates here:

https://gist.github.com/marbemac/a18582da8d2912285950/revisions

Usage is the same, just no more conflicts, and access to query.cursors now.

**Comment by JohnPostlethwait** [comment]
@marbemac Ah, that makes sense, thanks for the revision!

**Comment by christianalfoni** [comment]
There seems to be a lot of different approaches to how you would want to integrate Baobab with React. Maybe it would be an idea to have a "mixins" folder included with Baobab? Where proven mixins are added and documented? So you could choose the mixin that works best with your strategy and app. Like:

```js
var Baobab = require('baobab');
var QueryMixin = require('baobab/mixins/QueryMixin');
var tree = new Baobab({
  channels: []
}, {
  mixins: [QueryMixin]
});

var React = require('react');
module.exports = React.createClass({
  mixins: [tree.mixin]
});
```
So maybe if no mixins are defined, you include the default one, but as soon as you start defining mixins you get full control and can choose something that fits your strategy?

**Comment by ivan-kleshnin** [comment]
Does anyone considered doing filtering inside `componentWillUpdate`? 
It misses first load but data is empty there in general. 
This should be much more powerful than facets, because facets are based on a single cursor state, right? If filters are also state / cursors (representing our filter fields) how would those facets apply them to model index?

**Comment by Yomguithereal** [comment]
If a filtering is used only by one single component, then, yes, you should definitely perform it at component level in any hook you see fit.

Facets are only useful if you know you will use a filtered version of your data in multiple parts of your application and if you need to listen to changes only on the filtered elements and not the whole list itself to better tune your rendering.

**Comment by ivan-kleshnin** [comment]
> Facets are only useful if you know you will use a filtered version of your data in multiple parts of your application and if you need to listen to changes only on the filtered elements and not the whole list itself to better tune your rendering.

Yes. It's hard to discover the best possible API here, I know. Good luck with that!

**Comment by Yomguithereal** [comment]
@RJ, the `$cursor` feature is now implemented in the v1 branch.

**Comment by RJ** [comment]
@Yomguithereal yep just noticed, thanks! will try it out at the weekend.

**Comment by Yomguithereal** [comment]
Facets and `$cursor` are now working in v1.
