### ISSUE TITLE
Is it possible to replace contents of an entire tree at once?

### ISSUE THREAD

**Issue by bebraw** [Yomguithereal/baobab#169]
I am trying to achieve something like this:

```javascript
var rootCursor = emptyTree.root();

rootCursor.on('update', function() {
  console.log('updated', rootCursor.get()); // empty tree
});

rootCursor.edit({
  lanes: [
    {
      name: 'demo',
      todos: [{task: 'foo'}]
    }
  ]
});
```

For some reason (probably user error) the tree stays empty after modification. Is there a nice way to achieve this?

**Comment by Yomguithereal** [comment]
Hello @bebraw. For a reason I do not exactly recall, replacing the whole tree is not working on `v0.4.x` and before.

This should be working on the incoming `v1` however (on branch v1) which should be sufficiently stable now. I will release a `1.0.0-rc1` soon on npm. However a lot of changes have been made and they are not currently documented thoroughly.

If you need a dirty workaround for now, here is what you can do:

1) Store an object like `{root: yourData}` and edit the `root` key.
2) Change the tree data likewise:

```js
tree.data = yourData;
tree.emit('update', {log: [[]]});
```

I'll see whether I have time to fix this on `v0.4.x` before switching to v1 so that you could avoid using such schemes.

**Comment by bebraw** [comment]
Alright. Great to hear!

I asked this as I'm working on [a baobab chapter](https://github.com/survivejs/webpack/blob/master/manuscript/07_from_todo_to_kanban.md) for my book. Let me know if you notice obvious bits to improve. :)

**Comment by milanlandaverde** [comment]
+1

**Comment by romanonthego** [comment]
+1
get caught on this one, spend some time debugging :)

**Comment by Yomguithereal** [comment]
v1 is now published and should take care of this nasty bug.
