### ISSUE TITLE
ES6 iterable support?

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#201]

**Comment by AutoSponge** [comment]
Since I use ES6 full-time now, I was wondering if anyone had tried a Map, WeakMap, Set, or WeakSet implementation. 

I have a real-world scenario (my last project) where two ES6 Maps were used to keep two Sets "linked" without modifying the original data members. However, the real opportunity here was to have an abstraction that allowed a single "set" action to update both Maps. To my knowledge, that's not something that BB currently does.

**Comment by Yomguithereal** [comment]
I personally use the Set quite often because I am accustomed to set operations on other high-level languages and this is quite convenient.

However, I tend not to rely to much on Weak implementation in ES5 because they are either not performant or with quirks at some extent.

The thing which is frustrating with ES6 maps, but this is normal, is that they work through references and not value. Which make some of the Lispy languages' tricks a bit useless like using an array as a key. Still need to create weird string hashes.
