### ISSUE TITLE
Remove $cursor selector?

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#204]
Hi @Yomguithereal ,

I am working on the article and now I introduce the {$cursor: ['path']} before facets. What I notice though is that $cursor is not currently doing what you want it to do.

```js
var MyComp = React.createClass({
  mixins: [branch],
  cursors: {
    projects: ['projects', {$cursor: ['currentProjectId']}]
  }
});
```
There are two problems here:

1. The cursor does not update when the *currentProjectId* updates (Which we agreed is a bug)
2. If the project updates inside the *projects* cursor it does not update either? (Which is also a bug?)

The thing is that a facet solves this issue and more clearly defines what cursors are active. Thought I like what $cursor does, it just makes the API more complex and hides its implementation details compared to:

```js
var projectFacet = {
  cursors: {
    projects: ['projects'],
    id: ['currentProjectId']
  },
  get: function (data) {
    return data.projects[data.id];
  }
}
```

I am a big fant of writing more syntax to reduce API alternatives and hiding implementation details. The facet syntax tells the developer what it actually does, which the $cursor does not.

Anyways, just my 2 cents. Let me know if you want the $cursor in the article, but I think it is wise to move it to a "you can also do it like this" later on... as FACETS is the really awesome thing here :-)

**Comment by Yomguithereal** [comment]
My opinion here is that `$cursor` is just sugar. It's just a hidden bonus of the library, not one of its main feature like facets are. As such, I do not document them very conspicuously (even more since I should fix them ;-)). I wouldn't showcase them in a blog article, for instance. To me it's more of a "you can also do it like this" thing indeed.

**Comment by christianalfoni** [comment]
Cool! I agree :-)

**Comment by JohnAmican** [comment]
I ran into into something similar. I tried writing a facet like this, which didn't work (excuse the CS syntax):

```coffeescript
selectedUserOrders:
  cursors:
    selectedOrders: ['users', {$cursor: ['selectedUserId']}, 'orders']
  get: (data) ->
    data.selectedOrders
```

Maybe it was wishful thinking that it would realize that it should listen to updates on `'selectedUserId'`? :smile:. This works though:

```coffeescript
selectedUserOrders:
  cursors:
    users: ['users']
    selectedUserId: ['selectedUserId']
  get: (data) ->
    data.users[data.selectedUserId]?.orders
```

Would be nice to have the former because the use and intent of `selectedUserId` are co-located, whereas in the latter case I have not constrained myself at all with those cursor declarations; I could use them for anything when really I'm just going to use it to build a path of sorts.

BTW, fantastic library! Thanks so much!

**Comment by Yomguithereal** [comment]
Thanks @JohnAmican.

The `$cursor` not listening to the correct paths is clearly a bug (related to #196) and shall be corrected in a near future.

**Comment by Yomguithereal** [comment]
On a side note @christianalfoni, @JohnAmican, @RJ: did you have time to test the `$cursor` thingy and do you think it's really valuable over facets? The code associated to the feature is a bit messy and hard to clean so I was wondering whether I should keep it.

**Comment by RJ** [comment]
i'm currently using a combination of facets and cursors defined by a function that can access this.props.

Haven't needed the $cursor thing since i've done that, but i'm only testing this on a small experimental project. I am much more interested in a general nested facet api (alluded to in #226) than the $cursor thing :)

**Comment by christianalfoni** [comment]
Hi there,

My opinion is that $cursor should be removed. It is easier to learn Baobab if you only have Facets to do dynamic stuff. And Facets can do what $cursor does and Facets does it "inside the application state", not in the components, which I think is the right place to do it :-)

**Comment by Yomguithereal** [comment]
Question for you @christianalfoni, @RJ: would you go to v2 by removing $cursor or do you think it is benign enough not to generate a semver major?

**Comment by christianalfoni** [comment]
Oh... good question. I do not think there is a right answer for that one. Technically it is v2 in regards of breaking API? But its such a minor break I believe By default NPM only updates minor versions anyway so nobody should have a "sudden break". 

So to conclude, fits more with a major version change and "NOTE!!!" on release info I think :-)

**Comment by Yomguithereal** [comment]
By major version change you mean a minor 1.2.0 with a NOTE or a 2.0.0?

**Comment by christianalfoni** [comment]
Ah, sorry, yeah... 1.2.0 with a NOTE. NPM updates patch versions by default.

**Comment by Yomguithereal** [comment]
`$cursor` is now dropped in V2.
