### ISSUE TITLE
Investigate core related non syncwrite quirk

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#256]

**Comment by AutoSponge** [comment]
Not sure if this is related, but I've been able to replicate it in my application.

When using `syncwrite: false`, if a `$merge` transaction is on the tree and another transaction hits before the commit:

```javascript
this._transaction = (skipMerge && !Object.keys(this._transaction).length) ? spec : merge(this._transaction, spec);
```

This seems to wipe it out. I think the problem comes when the `merge(a, b)` fires and `a` has `$merge` property but since only `b.$merge` is checked, `a.$merge` is lost by the end of the transaction.

**Comment by Yomguithereal** [comment]
This is indeed a tough one @AutoSponge. Do you need a fix for V1?

**Comment by AutoSponge** [comment]
Nope, I'm using options settings to work around the issue.
