### ISSUE TITLE
Proposition: different cursor setters return

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#261]
@jacomyal @christianalfoni @ivan-kleshnin @scabbiaza:

For the time being cursors setters return the cursor itself so we can chain setters likewise:

```js
cursor
  .set([])
  .push('one')
  .push('two');
```

But, in a `syncwrite` workflow maybe cursors setters should return the resultant value?

```js
const array = cursor.set([1, 2, 3]);
```

On a side note @christianalfoni, it seemed `cerebral` gave you use cases where `syncwrite` wasn't hip. Any update? (sorry for the spamming).

**Comment by ivan-kleshnin** [comment]
I think it's a good idea and I actually wanted to proposed it. 
Can't speak for everyone but I never used piping possiblity for `set` and co.
`get` is a terminal operator and I prefer to keep symmetry between their usages.

It should be convenient to "refresh" variables. Something that would require additional read otherwise.

```
let counter = ...
...
counter = cursor.apply(c => c + 1);
```

It's not possible with the `const` statemement of course.

**Comment by Yomguithereal** [comment]
This is now the behavior in v2.
