### ISSUE TITLE
Uncaught error in facet.js when same cursor is updated twice in same "update" event

### ISSUE THREAD

**Issue by tnrich** [Yomguithereal/baobab#265]
Here's what the error looks like:

Uncaught TypeError: Cannot convert undefined or null to object

The cursors object is null
On line 134 of facet.js:
```
// Tracking the tree's updates
  function cursorsPaths(cursors) {
    return Object.keys(cursors).map(function(k) {
      return cursors[k].solvedPath;
    });
  }
```

I suspect that it is caused by the facet's cursor being updated twice in the same update tick. (Dunno if it's relevant, but II have syncwrite set to true) Whenever I see this error, In the this.log array, I see the same path twice:

On line 181 of boabab.js:
```
// Baobab-level update event
  this.emit('update', {
    log: this.log,
    previousState: this.previousData
  });
```

Example: 
```
this.log = [
  [
    0: "vectorEditorState"
    1: "sequenceData"
  ],
  [
    0: "vectorEditorState"
    1: "sequenceData"
  ]
]
```

Have you seen this before? Am I doing something incorrectly by calling set on the same cursor multiple times in quick succession? 

Many Thanks!

**Comment by Yomguithereal** [comment]
Hello @tnrich,
The duplicated log shouldn't be an issue since the facet will solve the update by breaking on the first item but yes, in the future, the log should be uniq'ed.

I think I had this bug a while ago. Are you using Baobab with React? If yes this is happening because of the event emitter's behavior (which is based upon node's one).

Could you try to check whether the latest version of the code on this repository fixes your issue, I think I committed something to fix an issue of the kind a while ago.

**Comment by tnrich** [comment]
hey @Yomguithereal, I pulled your most recent code directly from github and the error I was spotting seems to have disappeared. Thanks!

**Comment by Yomguithereal** [comment]
I'm glad to hear it @tnrich!
