### ISSUE TITLE
Performance of push has O(n)

### ISSUE THREAD

**Issue by ayalpani** [Yomguithereal/baobab#268]
Hi @Yomguithereal

in our application, the main baobab-managed data structure is an array. We now realized that the runtime of each push operation climbs with growing array size. In fact, the runtime seems to be O(n) as the push operation copies the whole array as can be seen here:

https://github.com/Yomguithereal/baobab/blob/master/src/update.js#L112

Here is a Script that pushes 100.000 items into a baobab array and plots out the runtime per 1000 push operations (the output can easily be dropped into a spreadsheet to draw a graph from it):

https://gist.github.com/ayalpani/7d66c4f2c87641bdcdd6#file-test-js

On my machine, the first 10.000 array items are pushed within 647 ms while items 90.000-100.000 take 11616 ms

I understand that you are cloning the array to enable immutability. If immutable option is turned off, couldn't you use native JavaScript methods like *Array.prototype.push* in general? This would enable a faster runtime when possible.

Best, Arash

**Comment by Aetet** [comment]
:+1:

**Comment by Yomguithereal** [comment]
Hello @ayalpani, before being immutable, Baobab is a persistent data structure. This means I need to shift references of the objects affected by your updates so you can do the following:

```js
ancientArray !== currentArray
```

If I use `push` and mutate the affected reference, I cannot do this anymore and the data structure is not persistent anymore.

The problem is, in JavaScript, if you want to make a different reference on an array, you have to copy it, hence the O(n). I don't know an other way to perform that. Would you @ayalpani or @Aetet know another way to do so?

I could provide a flag to disable persistence for performance reasons but this would be kinda missing the point of Baobab.

What you could do @ayalpani, as a workaround and if you don't care about immutability nor persistence and you know this kind of mutability won't affect anything, is try this:

```js
var array = cursor.get();
array.push(myNewValue);
cursor.set(array);
```

**Comment by Yomguithereal** [comment]
However, I think I actually use `Array.slice` to copy arrays and this is notoriously slow. Let me change this to a better for loop and let's see whether performances are better for you.

**Comment by chcokr** [comment]
Just a quick thought - https://github.com/petkaantonov/deque seems to have a very performant array/queue structure.

**Comment by Yomguithereal** [comment]
Hello @chcokr. I could of course implement a better data structure but I am not sure I want to do this. One of the goals of Baobab is to remain light and enable its user to manipulate raw JavaScript objects from the tree, not some different abstraction. To enable this, I would need to convert from my internal data structure to raw JavaScript objects on any `get` by the user and I feel it would translate in performance drops for most of the use cases of the library.

**Comment by ivan-kleshnin** [comment]
I'm trying to use Baobab to handle 3D graphics data (very big vectors) and it turns out to be very slow.
I think the reason is this "id rotation".

> This means I need to shift references of the objects affected by your updates so you can do the following ancientArray !== currentArray

This is very React (Component) oriented. I create WebGL viewport from React component and have a data in Baobab which is not handled by React (React Component just does not care). This data should not be "rotated" because it's not pass through any comparison pipeline.

Can I disable this "rotation" somehow to measure performance gain?

**Comment by ivan-kleshnin** [comment]
> If I use push and mutate the affected reference, I cannot do this anymore 

What do you mean by this? You can compare arrays and they will be equal by shallow comparison and not equal by deep comparison. Why should the whole Baobab architecture be made upon naturally wrong shallow comparisons?

**Comment by Yomguithereal** [comment]
Baobab is a persistent data structure. This means that it will only shift the actually affected references in the tree to reuse the not affected one in its next version. This is very useful when you want to perform "time travel" into the tree or do O(1) comparisons on complex & nested data structure. Else the only way you have to know whether two arrays/objects are different is to perform a shallow/deep diff which comes at a cost.

But yes, since Baobab relies on standard JavaScript objects for read/write perf reasons affecting huge arrays comes at a cost since shifting an array's reference is actually impossible without cloning the said array.

I plan to add soon an option to disable persistence and enable internal mutations again for performance but this is maybe broader than Baobab's scope to handle something else than an app's state. What you'd need is to enable persistence on some path but not others?

For the time being, you can also disable immutability and mutate the wanted array.

**Comment by ivan-kleshnin** [comment]
Complex stuff. I need some time to think it out.

**Comment by Yomguithereal** [comment]
One other thing here is that I cannot provide both easy immutability/persistence AND raw JavaScript objects to the user without a cost. The thing is I could implement a full-fledged data structure with efficient immutability and persistence but this would mean ~triple/quadruple the size of the lib while having a huge perf cost when converting to raw JS and I am not sure this is what I want since `immutable-js` and `mori` would probably do a better job than me here.

But I am thinking to implement a simple persistence/immutability blacklist as an option to handle specific cases as a middle ground as well as option to disable persistence.

**Comment by Yomguithereal** [comment]
For instance also, without persistence, I cannot offer your the `previousData` of the tree.

**Comment by Yomguithereal** [comment]
I just added a `persistent` option to the tree (available from `2.0.0-dev9`) for you to experiment. Just turn it off and you should see massive performance benefits on array manipulation. But then, you'll also lose previous states manipulation and efficient comparisons.

**Comment by ivan-kleshnin** [comment]
So let me reiterate. Library needs cheap comparisons because it does a lot of them. By id rotation you were able to replace full scans with `===` identity checks. If we don't rotate, the performance of data change grows but the overall performance falls down. 

It means the data which constantly changes could be better implemented without rotation, while other types of data benefit from current solution, am I right? But you say it can't be (easily?) implemented on cursors / facet level. I don't quite understand why and it seems I don't quite understand what do you mean by **persistence**.

> For instance also, without persistence, I cannot offer your the previousData of the tree.

Why?

> I just added a persistent option to the tree (available from 2.0.0-dev9) for you to experiment. Just turn it off and you should see massive performance benefits on array manipulation. But then, you'll also lose previous states manipulation and efficient comparisons.

Thank you, I will check it out and report about results.

**Comment by ivan-kleshnin** [comment]
> I'm trying to use Baobab to handle 3D graphics data (very big vectors) and it turns out to be very slow.
I think the reason is this "id rotation".

The reason was `immutable` flag. As I turned it off, performance was improved in orders of magnitude.
The difference between `{immutable: false, persistent: true}` and `{immutable: false, persistent: false}` is minor. I think you can get rid of this flag.

**Comment by Yomguithereal** [comment]
Out of curiosity @ivan-kleshnin, on what browser did you perform your tests? Iteration over frozen objects is notoriously slow on some browsers. However I am amazed that turning persistence off doesn't improve your performance drastically as there are no more cloning involved and as objects are mutated.

**Comment by ivan-kleshnin** [comment]
Latest Chrome Canary. 

> However I am amazed that turning persistence off doesn't improve your performance drastically as there are no more cloning involved and as objects are mutated.

There was some difference but it was absolutely insignificant to what happens with `immutable: true`.
Up to 10% comparing to 1000% growing with every write iteration. I think there (in Browser?!) is some problem with garbage collection of freezed objects.

**Comment by Yomguithereal** [comment]
That is likely indeed. This is why I am sure people should disable immutability for production.

**Comment by ivan-kleshnin** [comment]
And in some cases even for development :smile:

**Comment by Yomguithereal** [comment]
Is your 3D graphics project available somewhere? I'd love to see what it could look like.

**Comment by ivan-kleshnin** [comment]
Ah, thank you. This is under NDA, but I could possibly share some business-agnostic details with you, as soon as it will be more solid. It's a sandbox-level sketches for now.

**Comment by ribalba** [comment]
Hey @Yomguithereal,

I work with @ayalpani and we are seeing a huge increases in performance. Pretty much what you would expect from JS native. Which is what you are doing looking at the patch. I would love to see this in the new version. Would help us loads.

Cheers Didi

**Comment by Yomguithereal** [comment]
Hello @ribalba. Is that related to the `persistent` flag? Or to the latest updates of the `dev` version? Anyway, all updates made in the recent dev patches should be included in v2 normally.
