### ISSUE TITLE
Updates event for equal objects

### ISSUE THREAD

**Issue by markuplab** [Yomguithereal/baobab#320]
Update events trigger when object don't updated. It's look normally?

![2015-07-31 12 39 48](https://cloud.githubusercontent.com/assets/4974184/9002063/e5b3f110-3778-11e5-9797-e7e7f3cccc7a.png)

**Comment by Yomguithereal** [comment]
For now yes this is the expected behavior if you set a path to the exact same. However, I am thinking to change this but I'm still wondering whether I should add a `pure` option to the tree or make this new behavior default. I cannot remember now but I think I found some cases where the tree does not update were a bit too magical for the user.

**Comment by markuplab** [comment]
Yes, i think option or event with different name best way for realize it.

**Comment by Yomguithereal** [comment]
Option is now default on v2.
