### ISSUE TITLE
[v2] select from array with object doesn't work as filter

### ISSUE THREAD

**Issue by deepsweet** [Yomguithereal/baobab#331]
```js
import Baobab from 'baobab';

const tree = new Baobab({
    foo: [
        { bar: true, id: 1 },
        { bar: true, id: 2 }
    ]
});

console.log(
    tree.get([ 'foo', { bar: true } ])
);
// { bar: true, id: 1 }
// but not [ { bar: true, id: 1 }, { bar: true, id: 2 } ]
```

and this is totally unexpected behavior for me :scream_cat: how to get all array items with `bar: true`?

```js
console.log(
    tree.get([ 'foo', item => item.bar === true ])
);
/// the same { bar: true, id: 1 }
```

**Comment by Yomguithereal** [comment]
Hello @deepsweet. As explained in the documentation, the function selector will return the first matched object as with lodash's `find` function, for instance. This is because you cannot have a cursor pointing at several nodes of the tree.

To do what you want to do, just retrieve your array and use the filter method on it:

```js
tree.get('foo').filter(item => item.bar);
```

**Comment by deepsweet** [comment]
ok, I got it, thanks.
