### ISSUE TITLE
Discussion / Feature Request: Promises.

### ISSUE THREAD

**Issue by DylanPiercey** [Yomguithereal/baobab#355]
I was thinking about how I am commonly using baobab came across an idea; Return lazy promises for getters.

This would have a couple benefits:
+ Using a new promise at any level to represent a change in value could be used for quick strict equality.
+ Async updates to state could be the default without being annoying.
+ Consistent api for async and sync data; Setting a value that is deferred would be easy.
+ Async `monkeys` could also resolve async values.
+ Would work with async/await.

```javascript
// Setting an async value (same as now)
cursor.set("pageHTML", fetch("google.ca").then(res => res.text())
cursor.get("pageHTML").then(data =>...)  // returns a promise that resolves the provided value.

// Setting a sync value
cursor.set("pageHTML", "<html>...</html>")
cursor.get("pageHTML").then(data =>...) // returns a promise that resolves the provided value.
```

This would also allow (if implemented correctly) the ability to serialize async state, and then rehydrate the tree (perhaps for isomorphic rendering) and have everything revert back to promises. 

Theres probably some issues with this, and I may not have explained it clearly enough but I am just curious to see your opinions.

**Comment by Yomguithereal** [comment]
While I guess the possibility of using async setters would be a good thing, in some cases, I feel that obliging the use of Promises for every get/set scenario would make the API very tedious and the tree very uncomfortable to use, no?

**Comment by MichaelOstermann** [comment]
If I may add something to this, I would agree with @Yomguithereal that it might get tedious, especially the set method. You could do this anyway like

```javascript
fetch('google.ca')
.then(function(res) {
    cursor.set('pageHTML', res.text());
})
.catch(...);
```

Otherwise things become unclear:

```javascript
cursor.set("pageHTML", 
    fetch("google.ca")
    .then(res => res.text()) // what happens if fetching fails here, it is unclear how baobab would handle this
)
.then() // cursor.set successful?
.catch() // cursor.set failed?
.always() // what if I start to want this?
```

Also, depending on which promise implementation you would use, you would either have one that works synchronously or one that resolves on the next tick - I think it's not so good to force async if you do not have to technically, I'm using baobab synchronously and I think other people will do too.

Getting values could also be a bit annoying since you can not just 

```javascript
var a = cursor1.get();
var b = cursor2.get();
```

Instead you would have to "work around" it like

```javascript
Baobab.promise.all(cursor1.get(), cursor2.get())
.then(function(a, b) {
});
```

Or in the case of chaining:

```javascript
cursor1.get()
.then(function(value) {
    return cursor2.get(value);
})
.then(...)
```

The way I'm personally currently handling this is that I have a minimal wrapper around Baobab with for example fetch methods which I execute, when that request has been resolved I updated the tree with the response as well as setting a flag, to which I listen to and then grab the response data as usual.

**Comment by DylanPiercey** [comment]
@Yomguithereal I think this wouldn't be a burden for two reasons.

1) If your using react, or a vdom, likely you are going to use a facade like "react-baobab" and the async bits could be handled externally.
2) `async/await` semantics will make async javascript easy to reason about even for those who barely understand promises.

@MichaelOstermann 
The only thing I am saying should change is that all set values should resolve to promises.

```javascript
// This is exactly the same as it is currently.
cursor.set("pageHTML", 
    fetch("google.ca")
    .then(res => res.text())
)

// This resolves to a promise when "got"
cursor.set("count", 2)
cursor.get("count").then(count => ...)
```

Also it makes the most sense to use native promises and expect a polyfill where not available, the api is fairly intuitive and relied upon by many libraries (obviously including internals like fetch).
Things like `Promise.all` could be taken care of by wrapper libraries/facades like `react baobab.

I'm not sure this is a good fit for this library but thinking about the benefits and api symmetry I thought I would share!

**Comment by ivan-kleshnin** [comment]
-1 from me. Promises are crap.

**Comment by stacklance** [comment]
Agree whole heartedly with @ivan-kleshnin
