### ISSUE TITLE
loop a collection and apply a function

### ISSUE THREAD

**Issue by hyusetiawan** [Yomguithereal/baobab#356]
I have an array in the following format [{id: 1, name: 'bla', isSelected: false}]
what I want to do is to loop through the array and change the isSelected property with a simple comparison.

I have tried using apply() and map() (which is surprisingly undocumented? saw this in one of the issues) without success
the one that works for me is this:
```
var items = tree.select('items')

for(var i = 0; i < items.length; i++){
      tree.set([i, 'isSelected'], items[i].id == selected.id)
}
```
this does not seem right, how would I do it with a map() or apply()?

**Comment by hyusetiawan** [comment]
I forgot to put my attempt for the apply()
```
cursor.apply(function(items){
            for(var i = 0; i < items.length; i++){
                var item = items[i]
                item.isSelected = item.id == selectedCat.id
            }
            return items
        })
```

the cursor does not get updated

**Comment by Yomguithereal** [comment]
Hello @hyusetiawan. You're right the `cursor.map` method is not documented and I should write its docs. Basically it will iterate over the array contained by a cursor by providing you each sub cursor.

But, back to your example (I will assume you use the v2): the tree's data is immutable. So doing something like `item.isSelected = item.id == selectedCat.id` cannot work since immutable data cannot be mutated. Try putting `'use strict';` at the top of your code and normally it should throw telling you you cannot perform such thing.

So here what you could do to handle this problem (even though your first guess was quite good actually):

*Iterating on the sub cursors*

```js
// cursor.map
cursor.map(function(itemCursor) {
   var data = itemCursor.get();
   itemCursor.set('isSelected', data.id === whatever);
});

// variations exists of course
```

*Disabling the tree's immutability if it does not suit you (not advisable)*

```js
new Baobab(..., {immutable: false});
```

**Comment by hyusetiawan** [comment]
Thank you for the answer, yeah I thought it was the immutable nature of it, I do prefer having it immutable :)
So, I took my example from: https://github.com/Yomguithereal/baobab/wiki/Apply
specifically this part
```
tree.select('user').apply(function (user) {
  user.age = 32;
  return user;
});
```
I assume the wiki is not valid anymore.

**Comment by Yomguithereal** [comment]
Indeed, the wiki is unfortunately vastly outdated now. If you use ES6/7 you can also use this handy solution using object rest spread:

```js
const newList = list.map(e => {...e, isSelected: whatever});
```
