### ISSUE TITLE
Traverse between "marked" points of the history

### ISSUE THREAD

**Issue by kress95** [Yomguithereal/baobab#367]
I'm using baobab to make a game, and I wanted to save snapshots of the tree at the start of each game tick, it's almost like the history feature, but instead of traversing between state changes, I wanted to traverse between the initial states of the game ticks.

My initial idea was to mark the history somehow, but I don't know, maybe there's a better way to do it.

**Comment by kress95** [comment]
Found a kinda hacky way to do it (saving the tree state to a separate object and restoring it when needed).

**Comment by Yomguithereal** [comment]
Hello @kress95. The solution is indeed to store your tree's state and archive it somewhere in an index with a hashed key or something so you can retrieve it and then just reset the tree indeed. Since the tree is persistent (it will fail of course if you disable the tree's persistence) the history can be stashed easily.

**Comment by kress95** [comment]
I'm using it only for debug purposes, so no problems with disabling tree persistence during "real" gameplay. Thanks for attention :+1:
