### ISSUE TITLE
Monkey cannot be nested in an array

### ISSUE THREAD

**Issue by wBingwei** [Yomguithereal/baobab#369]
When monkey is defined in an object's property, it works fine, but when defining monkey in an element of an array, then the monkey's value will not be evaluated.

Here is the [Fiddle](http://jsfiddle.net/wj0x0a5q/2/) code to demonstrate this issue.

Is this a defect?

**Comment by Yomguithereal** [comment]
Hello @wBingwei. This is, for the time being, an expected behavior (an undocumented one though, my bad). I don't allow monkeys beneath array because it might get very heavy and trigger some nasty performance drops. But I am not opposed to implement it in a further minor version.

Can you elaborate on your use case so we can discuss this please?

**Comment by wBingwei** [comment]
Thanks for your explanation, I also think it might get heavy for our tree. And I don't think our case is a good one, we have done it without monkey.

Thank you again.
