### ISSUE TITLE
shiftReferences to true by default?

### ISSUE THREAD

**Issue by Yomguithereal** [Yomguithereal/baobab#86]
@christianalfoni, any opinion on this?

**Comment by christianalfoni** [comment]
It depends. I got one comment on this flux-angular lib I have been working on. Shifting references will cripple objects that inherits from something else than Object. Lets say you wanted to put an instance of a class you have created that has its own prototype. If that object was changed by the Baobab API the object would loose its prototype.

That said. An instance of an object with some custom prototype should implement a constructor property on the prototype. 

```javascript
function MyConstr () {}
MyConstr.prototype = {
  constructor: MyConstr,
  myMethod: function () {}
};
```

So if you make this default I suggest that the code where you change references on objects, you do this:

```javascript
// Some cursor that points to an object with custom prototype
var existingBaobabObjectValue = someCursor.get();

// Create a new object linking it to the prototype of the existingBaobabObjectValue
var newObject = Object.create(existingBaobabObjectValue.constructor.prototype);

// Move instance properties over to the new object
extend(newObject, existingBaobabObjectValue);

// Put it back
someCursor.edit(newObject);
```

I have not checked the source code of how it is done now, but hopefully this makes sense :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni, I am more and more considering putting `shiftReference` to true by default in the future. This would dramatically simplify the validation routine for instance by giving the opportunity to the user to get past and future state.

As I see it, you should not put anything else than "raw" data in the tree but I perfectly understand that I should try to clone correctly "irregular" objects. I'll try to see what I can do.

**Comment by christianalfoni** [comment]
Actually, you might be interested in this immutable-store I built, [immutable-store](https://github.com/christianalfoni/immutable-store), just as a daily input :-) It requires raw objects/array/primitives. 

I think `shiftReference` could be true by default, though it has to be clear in the documentation. There might be situations where you want to mutate objects and arrays in the tree without using the tree API. But I would think that developers using Baobab would want to use the tree API for all updates, as you do want to notify about all changes.

You know, if you decide to make it true by default you can get another benefit. You could copy the few lines of code from `PureRenderMixin` into the default mixin. Then you would not need any configuration at all working with React. It is just highly optimized straight out of the box :-)

A thought!

Btw, I can help you create a React section on the README, now that you got this tree values copied to state as default behavior. Got lots of experience using Baobab with React, shiftReference and PureRenderMixin now, so I think I could give some valuable input on that.

**Comment by Yomguithereal** [comment]
I don't really see situations where you want to mutate things on your own and if you want to do so you can as well wrap it into an `$apply` command.

I will think about integrating the purerendermixin but I fear that imposing it might lead to unexpected behaviour for some projects. Maybe a `purerender` setting or something similar.

Don't hesitate to contribute on the React section of the README. Your input is always welcome :)

**Comment by christianalfoni** [comment]
Hehe, thanks @Yomguithereal!

Yeah, its better to be safe than sorry, though I am very confident that it will not be a problem. Let me give some background.

**If you have a component** using the Baobab mixin, where PureRenderMixin is included, it will only update if the property values on the "props" or "state" object changes. Since you listen to one or more cursors the component will update when events triggers on the respective cursors. The component will also update if a parent passes a property with a changed value. It could of course also update if it changes its internal state.

If a child of a component using the mixin does not use the mixin itself it will render whenever the parent renders, which is what you expect. The only way a child can render without its parent is if it listens to a cursor.

There is no way a child would want to render without a change on the parent, passing props, changes its own state or listens to a cursor. 

But yeah, its just a small config, and it would be quite embarrassing if something bad would happen ;-) Could of course have `pureRender` default true, and set it to false just in case.

**Comment by andrewluetgers** [comment]
+1 on default to true with clear documentation of the change
