### ISSUE TITLE
Article published

### ISSUE THREAD

**Issue by christianalfoni** [Yomguithereal/baobab#89]
Okay,

Got the article out here: [Plan a Baobab tree in your FLUX application](http://christianalfoni.github.io/javascript/2015/02/06/plant-a-baobab-tree-in-your-flux-application.html). Hope you like, and let me know if there are some misunderstood concepts or typos :-)

**Comment by Yomguithereal** [comment]
Hello @christianalfoni. Thanks for your article! I do not use Flux per se, but I think the way we use Boabab is quite similar. I never understood the use of multiple stores (maybe the application I build are not complex enough to require multiple stores anyway) in Flux and prefer a single centralized state.

*Typos*

* `There are not many that handles`: `handle`
* `There er several implementations`: `There are`
* `Developers in the JavaScript world has become accustomed`: `have`
* `repetetive`: `repetitive`

Also, I saw this line in the beginning:

```js
notificationsCursor.select('isLoading').set(true);
```

This should not work as the `set` method takes both a key and a value. You probably meant:

```js
notificationsCursor.select('isLoading').edit(true);

// Or maybe this is clearer:
notificationsCursor.set('isLoading', true);
```

And a little tip: you wrote

```js
localStorage.state = JSON.stringify(stateTree.get());
```

but you can do the following also

```js
localStorage.state = JSON.stringify(stateTree);
```

since a baobab has a `toJSON` method.

Have a good day :)

**Comment by christianalfoni** [comment]
Thanks a lot for the review :-D I get totally blind after a while, hehe. Pushed the updates now, thanks again!
